name: Run Tests and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Set PYTHONPATH to the project root
        run: echo "PYTHONPATH=$(pwd)" >> $GITHUB_ENV

      - name: Run Tests with Coverage
        run: |
          pytest --cov=models tests/

      - name: Deploy to Render (if tests pass and on main branch)
        run: |
          curl -fsSL https://render.com/docs/deploy/github-action | bash

          curl -X POST https://api.render.com/v1/services/YOUR_SERVICE_ID/deploy \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            -d '{"branch": "main"}'